server:
  port: 8080

spring:
  datasource:
    url: 'jdbc:sqlite::memory:'

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    show-sql: true
    database-platform: com.enigmabridge.hibernate.dialect.SQLiteDialect